version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SIMPLIFIED_ONBOARDING_API_URL: https://api-onboarding.maskinporten.dev
    ports:
      - "3000:8080"
