---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-simplified-onboarding.yaml
  - service-simplified-onboarding.yaml
images:
  - name: simplified-onboarding
    newName: eu.gcr.io/digdir-fdk-infra/simplified-onboarding
    newTag: $(GIT_COMMIT_SHA)