---
apiVersion: v1
kind: Service
metadata:
  name: simplified-onboarding
spec:
  selector:
    app: simplified-onboarding
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort