---
apiVersion: v1
kind: Service
metadata:
  name: simplified-onboarding
spec:
  selector:
    app: simplified-onboarding
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort