---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplified-onboarding
  labels:
    app: simplified-onboarding
spec:
  selector:
    matchLabels:
      app: simplified-onboarding
  template:
    spec:
      containers:
        - name: simplified-onboarding
          env:
            - name: SIMPLIFIED_ONBOARDING_API_URL
              value: https://simplified-onboarding-api.staging.fellesdatakatalog.digdir.no
            - name: WHITELIST
              value: entur:apc.demo,entur:api.1,banenor:traffic.update.read,datanorge:test/catalog.read,datanorge:catalog.read,skatteetaten:kravogbetaling
